# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colab_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from threading import Thread

# Setting up Modbus communication
import Modbus_Server as modbus
server = modbus.ModbusTCPServer(host='10.0.12.249', port=502, no_block=True)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1394, 861)
        MainWindow.setStyleSheet("")

        # Setting the layout of the GUI
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(127, 127, 127);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.WidgetMenu = QtWidgets.QWidget(self.centralwidget)
        self.WidgetMenu.setMaximumSize(QtCore.QSize(500, 16777215))
        self.WidgetMenu.setStyleSheet("background-color:rgb(127, 127, 127)")
        self.WidgetMenu.setObjectName("WidgetMenu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.WidgetMenu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.WidgetJustifier = QtWidgets.QWidget(self.WidgetMenu)
        self.WidgetJustifier.setObjectName("WidgetJustifier")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.WidgetJustifier)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LogoJustifier = QtWidgets.QWidget(self.WidgetJustifier)
        self.LogoJustifier.setObjectName("LogoJustifier")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.LogoJustifier)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.LogoJustifier)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.logo = QtWidgets.QLabel(self.LogoJustifier)
        self.logo.setObjectName("logo")
        self.gridLayout_4.addWidget(self.logo, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.LogoJustifier, 0, 0, 1, 1)

        # Constructing the Page Selector Menu
        self.PageSelectors = QtWidgets.QFrame(self.WidgetJustifier)
        self.PageSelectors.setStyleSheet("background-color:rgb(153, 153, 153);"
                                         "border-style: outset;"
                                         "border-width: 2px;"
                                         "border-radius: 20px;"
                                         "border-color: grey;"
                                         "padding: 4px;")
        self.PageSelectors.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.PageSelectors.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PageSelectors.setLineWidth(1)
        self.PageSelectors.setMidLineWidth(0)
        self.PageSelectors.setObjectName("PageSelectors")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PageSelectors)
        self.verticalLayout.setObjectName("verticalLayout")

        # Constructing Demo 1 selector button
        self.Demo1PageBtn = QtWidgets.QPushButton(self.PageSelectors)
        self.Demo1PageBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Demo1PageBtn.setFont(font)
        self.Demo1PageBtn.setStyleSheet("QPushButton"
                                        "{"
                                        "background-color : lightgrey;"
                                        "border-style: outset;\n"
                                        "border-width: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}"
                                        "QPushButton::pressed"
                                        "{"
                                        "background-color : rgb(160, 160, 160);"
                                        "border-style: inset;\n"
                                        "border-width: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}")
        self.Demo1PageBtn.setFlat(False)
        self.Demo1PageBtn.setObjectName("Demo1PageBtn")
        self.verticalLayout.addWidget(self.Demo1PageBtn)

        # Constructing Demo 2 selector button
        self.Demo2PageBtn = QtWidgets.QPushButton(self.PageSelectors)
        self.Demo2PageBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Demo2PageBtn.setFont(font)
        self.Demo2PageBtn.setStyleSheet("QPushButton"
                                        "{"
                                        "background-color : lightgrey;"
                                        "border-style: outset;\n"
                                        "border-width: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}"
                                        "QPushButton::pressed"
                                        "{"
                                        "background-color : rgb(160, 160, 160);"
                                        "border-style: inset;\n"
                                        "border-width: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}")
        self.Demo2PageBtn.setObjectName("Demo2PageBtn")
        self.verticalLayout.addWidget(self.Demo2PageBtn)

        # Constructing Demo 3 selector button
        self.Demo3PageBtn = QtWidgets.QPushButton(self.PageSelectors)
        self.Demo3PageBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Demo3PageBtn.setFont(font)
        self.Demo3PageBtn.setStyleSheet("QPushButton"
                                        "{"
                                        "background-color : lightgrey;"
                                        "border-style: outset;\n"
                                        "border-width: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}"
                                        "QPushButton::pressed"
                                        "{"
                                        "background-color : rgb(160, 160, 160);"
                                        "border-style: inset;\n"
                                        "border-width: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}")
        self.Demo3PageBtn.setObjectName("Demo3PageBtn")
        self.verticalLayout.addWidget(self.Demo3PageBtn)

        # Constructing the About page selector button
        self.AboutPageBtn = QtWidgets.QPushButton(self.PageSelectors)
        self.AboutPageBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.AboutPageBtn.setFont(font)
        self.AboutPageBtn.setMouseTracking(False)
        self.AboutPageBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AboutPageBtn.setAutoFillBackground(False)
        self.AboutPageBtn.setStyleSheet("QPushButton"
                                        "{"
                                        "background-color : lightgrey;"
                                        "border-style: outset;\n"
                                        "border-width: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}"
                                        "QPushButton::pressed"
                                        "{"
                                        "background-color : rgb(160, 160, 160);"
                                        "border-style: inset;\n"
                                        "border-width: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoPrefix/about-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AboutPageBtn.setIcon(icon)
        self.AboutPageBtn.setIconSize(QtCore.QSize(40, 40))
        self.AboutPageBtn.setObjectName("AboutPageBtn")
        self.verticalLayout.addWidget(self.AboutPageBtn)
        self.gridLayout_3.addWidget(self.PageSelectors, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.WidgetJustifier, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.WidgetMenu, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.WidgetJustifier)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: black")
        self.label_12.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.WidgetJustifier, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.WidgetMenu, 0, 0, 1, 1)
        self.modbusConnectBtn = QtWidgets.QPushButton(self.WidgetJustifier)
        self.modbusConnectBtn.setObjectName("modbusConnectBtn")
        self.modbusConnectBtn.setStyleSheet("QPushButton"
                                            "{"
                                            "background-color : rgb(74, 255, 101);"
                                            "border-style: outset;\n"
                                            "border-width: 2px;\n"
                                            "border-radius: 10px;\n"
                                            "border-color: green;\n"
                                            "padding: 4px;"
                                            "}"
                                            "QPushButton::pressed"
                                            "{"
                                            "background-color : rgb(0, 226, 0);"
                                            "border-style: inset;\n"
                                            "border-width: 2px;\n"
                                            "border-radius: 10px;\n"
                                            "border-color: green;\n"
                                            "padding: 4px;"
                                            "}")
        self.modbusConnectBtn.setMinimumSize(QtCore.QSize(16777215, 40))
        self.gridLayout_3.addWidget(self.modbusConnectBtn, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.WidgetJustifier, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.WidgetMenu, 0, 0, 1, 1)
        self.modbusDisconnectBtn = QtWidgets.QPushButton(self.WidgetJustifier)
        self.modbusDisconnectBtn.setObjectName("modbusDisconnectBtn")
        self.modbusDisconnectBtn.setStyleSheet("QPushButton"
                                               "{"
                                               "background-color : rgb(255, 83, 108);"
                                               "border-style: outset;\n"
                                               "border-width: 2px;\n"
                                               "border-radius: 10px;\n"
                                               "border-color: red;\n"
                                               "padding: 4px;"
                                               "}"
                                               "QPushButton::pressed"
                                               "{"
                                               "background-color : rgb(255, 50, 75);"
                                               "border-style: inset;\n"
                                               "border-width: 2px;\n"
                                               "border-radius: 10px;\n"
                                               "border-color: red;\n"
                                               "padding: 4px;"
                                               "}")
        self.modbusDisconnectBtn.setMinimumSize(QtCore.QSize(16777215, 40))
        self.gridLayout_3.addWidget(self.modbusDisconnectBtn, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.WidgetJustifier, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.WidgetMenu, 0, 0, 1, 1)
        self.whichDemoIsRunLabel = QtWidgets.QLabel(self.WidgetJustifier)
        self.whichDemoIsRunLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(16)
        font.setItalic(False)
        self.whichDemoIsRunLabel.setFont(font)
        self.whichDemoIsRunLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.whichDemoIsRunLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.whichDemoIsRunLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.whichDemoIsRunLabel.setObjectName("whichDemoIsRunLabel")
        self.gridLayout_3.addWidget(self.whichDemoIsRunLabel, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.WidgetJustifier, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.WidgetMenu, 0, 0, 1, 1)
        self.Widget_Contents = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Widget_Contents.sizePolicy().hasHeightForWidth())
        self.Widget_Contents.setSizePolicy(sizePolicy)
        self.Widget_Contents.setStyleSheet("background-color:rgb(153, 153, 153)")
        self.Widget_Contents.setObjectName("Widget_Contents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Widget_Contents)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Constructing the different pages
        self.WidgetPages = QtWidgets.QStackedWidget(self.Widget_Contents)
        self.WidgetPages.setObjectName("WidgetPages")

        # Constructing the page for Demo 1
        self.Demo1Page = QtWidgets.QWidget()
        self.Demo1Page.setObjectName("Demo1Page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Demo1Page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Demo1Label = QtWidgets.QLabel(self.Demo1Page)
        self.Demo1Label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Demo1Label.setFont(font)
        self.Demo1Label.setTextFormat(QtCore.Qt.PlainText)
        self.Demo1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Demo1Label.setObjectName("Demo1Label")
        self.verticalLayout_2.addWidget(self.Demo1Label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalFrame_2 = QtWidgets.QFrame(self.Demo1Page)
        self.verticalFrame_2.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                           "border-style: inset;\n"
                                           "border-width: 2px;\n"
                                           "border-radius: 20px;\n"
                                           "border-color: grey;\n"
                                           "padding: 4px;")
        self.verticalFrame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.verticalFrame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.ModbusInputDemo1Rob1 = QtWidgets.QLabel(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ModbusInputDemo1Rob1.setFont(font)
        self.ModbusInputDemo1Rob1.setStyleSheet("")
        self.ModbusInputDemo1Rob1.setText("")
        self.ModbusInputDemo1Rob1.setAlignment(QtCore.Qt.AlignCenter)
        self.ModbusInputDemo1Rob1.setObjectName("ModbusInputDemo1Rob1")
        self.verticalLayout_8.addWidget(self.ModbusInputDemo1Rob1)
        self.horizontalLayout_3.addWidget(self.verticalFrame_2)
        self.verticalFrame = QtWidgets.QFrame(self.Demo1Page)
        self.verticalFrame.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                         "border-style: inset;\n"
                                         "border-width: 2px;\n"
                                         "border-radius: 20px;\n"
                                         "border-color: grey;\n"
                                         "padding: 4px;")
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame.setLineWidth(1)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.verticalFrame)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.ModbusInputDemo1Rob2 = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ModbusInputDemo1Rob2.setFont(font)
        self.ModbusInputDemo1Rob2.setText("")
        self.ModbusInputDemo1Rob2.setAlignment(QtCore.Qt.AlignCenter)
        self.ModbusInputDemo1Rob2.setObjectName("ModbusInputDemo1Rob2")
        self.verticalLayout_7.addWidget(self.ModbusInputDemo1Rob2)
        self.horizontalLayout_3.addWidget(self.verticalFrame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.StartDemo1Btn = QtWidgets.QPushButton(self.Demo1Page)
        self.StartDemo1Btn.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.StartDemo1Btn.setFont(font)
        self.StartDemo1Btn.setStyleSheet("QPushButton"
                                         "{"
                                         "background-color : rgb(170, 170, 170);"
                                         "border-style: outset;\n"
                                         "border-width: 1px;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: grey;\n"
                                         "padding: 4px;"
                                         "}"
                                         "QPushButton::pressed"
                                         "{"
                                         "background-color : rgb(160, 160, 160);"
                                         "border-style: inset;\n"
                                         "border-width: 1px;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: grey;\n"
                                         "padding: 4px;"
                                         "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/LogoPrefix/start_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartDemo1Btn.setIcon(icon1)
        self.StartDemo1Btn.setIconSize(QtCore.QSize(100, 100))
        self.StartDemo1Btn.setCheckable(False)
        self.StartDemo1Btn.setObjectName("StartDemo1Btn")
        self.verticalLayout_2.addWidget(self.StartDemo1Btn)
        self.StopDemo1Btn = QtWidgets.QPushButton(self.Demo1Page)
        self.StopDemo1Btn.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.StopDemo1Btn.setFont(font)
        self.StopDemo1Btn.setStyleSheet("QPushButton"
                                        "{"
                                        "background-color : rgb(170, 170, 170);"
                                        "border-style: outset;\n"
                                        "border-width: 1px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}"
                                        "QPushButton::pressed"
                                        "{"
                                        "background-color : rgb(160, 160, 160);"
                                        "border-style: inset;\n"
                                        "border-width: 1px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/LogoPrefix/stop_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StopDemo1Btn.setIcon(icon2)
        self.StopDemo1Btn.setIconSize(QtCore.QSize(70, 70))
        self.StopDemo1Btn.setObjectName("StopDemo1Btn")
        self.verticalLayout_2.addWidget(self.StopDemo1Btn)
        self.WidgetPages.addWidget(self.Demo1Page)

        # Constructing the page for Demo 2
        self.Demo2Page = QtWidgets.QWidget()
        self.Demo2Page.setObjectName("Demo2Page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Demo2Page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Demo2Label = QtWidgets.QLabel(self.Demo2Page)
        self.Demo2Label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Demo2Label.setFont(font)
        self.Demo2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Demo2Label.setObjectName("Demo2Label")
        self.verticalLayout_3.addWidget(self.Demo2Label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalFrame_21 = QtWidgets.QFrame(self.Demo2Page)
        self.verticalFrame_21.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                            "border-style: inset;\n"
                                            "border-width: 2px;\n"
                                            "border-radius: 20px;\n"
                                            "border-color: grey;\n"
                                            "padding: 4px;")
        self.verticalFrame_21.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.verticalFrame_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame_21.setObjectName("verticalFrame_21")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalFrame_21)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.verticalFrame_21)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.ModbusInputDemo2Rob1 = QtWidgets.QLabel(self.verticalFrame_21)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ModbusInputDemo2Rob1.setFont(font)
        self.ModbusInputDemo2Rob1.setText("")
        self.ModbusInputDemo2Rob1.setAlignment(QtCore.Qt.AlignCenter)
        self.ModbusInputDemo2Rob1.setObjectName("ModbusInputDemo2Rob1")
        self.verticalLayout_10.addWidget(self.ModbusInputDemo2Rob1)
        self.horizontalLayout_4.addWidget(self.verticalFrame_21)
        self.verticalFrame1 = QtWidgets.QFrame(self.Demo2Page)
        self.verticalFrame1.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                          "border-style: inset;\n"
                                          "border-width: 2px;\n"
                                          "border-radius: 20px;\n"
                                          "border-color: grey;\n"
                                          "padding: 4px;")
        self.verticalFrame1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.verticalFrame1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.ModbusInputDemo2Rob2 = QtWidgets.QLabel(self.verticalFrame1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ModbusInputDemo2Rob2.setFont(font)
        self.ModbusInputDemo2Rob2.setText("")
        self.ModbusInputDemo2Rob2.setAlignment(QtCore.Qt.AlignCenter)
        self.ModbusInputDemo2Rob2.setObjectName("ModbusInputDemo2Rob2")
        self.verticalLayout_9.addWidget(self.ModbusInputDemo2Rob2)
        self.horizontalLayout_4.addWidget(self.verticalFrame1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.StartDemo2Btn = QtWidgets.QPushButton(self.Demo2Page)
        self.StartDemo2Btn.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.StartDemo2Btn.setFont(font)
        self.StartDemo2Btn.setStyleSheet("QPushButton"
                                         "{"
                                         "background-color : rgb(170, 170, 170);"
                                         "border-style: outset;\n"
                                         "border-width: 1px;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: grey;\n"
                                         "padding: 4px;"
                                         "}"
                                         "QPushButton::pressed"
                                         "{"
                                         "background-color : rgb(160, 160, 160);"
                                         "border-style: inset;\n"
                                         "border-width: 1px;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: grey;\n"
                                         "padding: 4px;"
                                         "}")
        self.StartDemo2Btn.setIcon(icon1)
        self.StartDemo2Btn.setIconSize(QtCore.QSize(100, 100))
        self.StartDemo2Btn.setObjectName("StartDemo2Btn")
        self.verticalLayout_3.addWidget(self.StartDemo2Btn)
        self.StopDemo2Btn = QtWidgets.QPushButton(self.Demo2Page)
        self.StopDemo2Btn.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.StopDemo2Btn.setFont(font)
        self.StopDemo2Btn.setStyleSheet("QPushButton"
                                        "{"
                                        "background-color : rgb(170, 170, 170);"
                                        "border-style: outset;\n"
                                        "border-width: 1px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}"
                                        "QPushButton::pressed"
                                        "{"
                                        "background-color : rgb(160, 160, 160);"
                                        "border-style: inset;\n"
                                        "border-width: 1px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}")
        self.StopDemo2Btn.setIcon(icon2)
        self.StopDemo2Btn.setIconSize(QtCore.QSize(70, 70))
        self.StopDemo2Btn.setObjectName("StopDemo2Btn")
        self.verticalLayout_3.addWidget(self.StopDemo2Btn)
        self.WidgetPages.addWidget(self.Demo2Page)

        # Constructing the page for Demo 3
        self.Demo3Page = QtWidgets.QWidget()
        self.Demo3Page.setObjectName("Demo3Page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Demo3Page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Demo3Label = QtWidgets.QLabel(self.Demo3Page)
        self.Demo3Label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Demo3Label.setFont(font)
        self.Demo3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Demo3Label.setObjectName("Demo3Label")
        self.verticalLayout_4.addWidget(self.Demo3Label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalFrame2 = QtWidgets.QFrame(self.Demo3Page)
        self.verticalFrame2.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                          "border-style: inset;\n"
                                          "border-width: 2px;\n"
                                          "border-radius: 20px;\n"
                                          "border-color: grey;\n"
                                          "padding: 4px;")
        self.verticalFrame2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.verticalFrame2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.verticalFrame2)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.ModbusInputDemo3Rob1 = QtWidgets.QLabel(self.verticalFrame2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ModbusInputDemo3Rob1.setFont(font)
        self.ModbusInputDemo3Rob1.setText("")
        self.ModbusInputDemo3Rob1.setAlignment(QtCore.Qt.AlignCenter)
        self.ModbusInputDemo3Rob1.setObjectName("ModbusInputDemo3Rob1")
        self.verticalLayout_11.addWidget(self.ModbusInputDemo3Rob1)
        self.AssemblyConfirmBtn = QtWidgets.QPushButton(self.verticalFrame2)
        self.AssemblyConfirmBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.AssemblyConfirmBtn.setStyleSheet("QPushButton"
                                              "{"
                                              "background-color : rgb(170, 170, 170);"
                                              "border-style: outset;\n"
                                              "border-width: 1px;\n"
                                              "border-radius: 10px;\n"
                                              "border-color: grey;\n"
                                              "padding: 4px;"
                                              "}"
                                              "QPushButton::pressed"
                                              "{"
                                              "background-color : rgb(160, 160, 160);"
                                              "border-style: inset;\n"
                                              "border-width: 1px;\n"
                                              "border-radius: 10px;\n"
                                              "border-color: grey;\n"
                                              "padding: 4px;"
                                              "}")
        self.AssemblyConfirmBtn.setObjectName("AssemblyConfirmBtn")
        self.verticalLayout_11.addWidget(self.AssemblyConfirmBtn)
        self.horizontalLayout_5.addWidget(self.verticalFrame2)
        self.verticalFrame_22 = QtWidgets.QFrame(self.Demo3Page)
        self.verticalFrame_22.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                            "border-style: inset;\n"
                                            "border-width: 2px;\n"
                                            "border-radius: 20px;\n"
                                            "border-color: grey;\n"
                                            "padding: 4px;")
        self.verticalFrame_22.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.verticalFrame_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalFrame_22.setObjectName("verticalFrame_22")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalFrame_22)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.verticalFrame_22)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.ModbusInputDemo3Rob2 = QtWidgets.QLabel(self.verticalFrame_22)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ModbusInputDemo3Rob2.setFont(font)
        self.ModbusInputDemo3Rob2.setText("")
        self.ModbusInputDemo3Rob2.setAlignment(QtCore.Qt.AlignCenter)
        self.ModbusInputDemo3Rob2.setObjectName("ModbusInputDemo3Rob2")
        self.verticalLayout_12.addWidget(self.ModbusInputDemo3Rob2)
        self.horizontalLayout_5.addWidget(self.verticalFrame_22)
        self.MobRobFrame = QtWidgets.QFrame(self.Demo3Page)
        self.MobRobFrame.setStyleSheet("background-color: rgb(179, 179, 179);\n"
                                       "border-style: inset;\n"
                                       "border-width: 2px;\n"
                                       "border-radius: 20px;\n"
                                       "border-color: grey;\n"
                                       "padding: 4px;")
        self.MobRobFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.MobRobFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MobRobFrame.setObjectName("MobRobFrame")
        self.MobileRobotFrame = QtWidgets.QVBoxLayout(self.MobRobFrame)
        self.MobileRobotFrame.setObjectName("MobileRobotFrame")
        self.MobRobStatusLabel = QtWidgets.QLabel(self.MobRobFrame)
        self.MobRobStatusLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.MobRobStatusLabel.setFont(font)
        self.MobRobStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MobRobStatusLabel.setObjectName("MobRobStatusLabel")
        self.MobileRobotFrame.addWidget(self.MobRobStatusLabel)
        self.ModbusInputMobRob = QtWidgets.QLabel(self.MobRobFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ModbusInputMobRob.setFont(font)
        self.ModbusInputMobRob.setText("")
        self.ModbusInputMobRob.setAlignment(QtCore.Qt.AlignCenter)
        self.ModbusInputMobRob.setObjectName("ModbusInputMobRob")
        self.MobileRobotFrame.addWidget(self.ModbusInputMobRob)
        self.MobRobConfirmBtn = QtWidgets.QPushButton(self.MobRobFrame)
        self.MobRobConfirmBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.MobRobConfirmBtn.setStyleSheet("QPushButton"
                                            "{"
                                            "background-color : rgb(170, 170, 170);"
                                            "border-style: outset;\n"
                                            "border-width: 1px;\n"
                                            "border-radius: 10px;\n"
                                            "border-color: grey;\n"
                                            "padding: 4px;"
                                            "}"
                                            "QPushButton::pressed"
                                            "{"
                                            "background-color : rgb(160, 160, 160);"
                                            "border-style: inset;\n"
                                            "border-width: 1px;\n"
                                            "border-radius: 10px;\n"
                                            "border-color: grey;\n"
                                            "padding: 4px;"
                                            "}")
        self.MobRobConfirmBtn.setObjectName("MobRobConfirmBtn")
        self.MobileRobotFrame.addWidget(self.MobRobConfirmBtn)
        self.horizontalLayout_5.addWidget(self.MobRobFrame)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.StartDemo3Btn = QtWidgets.QPushButton(self.Demo3Page)
        self.StartDemo3Btn.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.StartDemo3Btn.setFont(font)
        self.StartDemo3Btn.setStyleSheet("QPushButton"
                                         "{"
                                         "background-color : rgb(170, 170, 170);"
                                         "border-style: outset;\n"
                                         "border-width: 1px;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: grey;\n"
                                         "padding: 4px;"
                                         "}"
                                         "QPushButton::pressed"
                                         "{"
                                         "background-color : rgb(160, 160, 160);"
                                         "border-style: inset;\n"
                                         "border-width: 1px;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: grey;\n"
                                         "padding: 4px;"
                                         "}")
        self.StartDemo3Btn.setIcon(icon1)
        self.StartDemo3Btn.setIconSize(QtCore.QSize(100, 100))
        self.StartDemo3Btn.setObjectName("StartDemo3Btn")
        self.verticalLayout_4.addWidget(self.StartDemo3Btn)
        self.StopDemo3Btn = QtWidgets.QPushButton(self.Demo3Page)
        self.StopDemo3Btn.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.StopDemo3Btn.setFont(font)
        self.StopDemo3Btn.setStyleSheet("QPushButton"
                                        "{"
                                        "background-color : rgb(170, 170, 170);"
                                        "border-style: outset;\n"
                                        "border-width: 1px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}"
                                        "QPushButton::pressed"
                                        "{"
                                        "background-color : rgb(160, 160, 160);"
                                        "border-style: inset;\n"
                                        "border-width: 1px;\n"
                                        "border-radius: 10px;\n"
                                        "border-color: grey;\n"
                                        "padding: 4px;"
                                        "}")
        self.StopDemo3Btn.setIcon(icon2)
        self.StopDemo3Btn.setIconSize(QtCore.QSize(70, 70))
        self.StopDemo3Btn.setObjectName("StopDemo3Btn")
        self.verticalLayout_4.addWidget(self.StopDemo3Btn)
        self.WidgetPages.addWidget(self.Demo3Page)

        # Constructing the "About this project" page
        self.AboutPage = QtWidgets.QWidget()
        self.AboutPage.setObjectName("AboutPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.AboutPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.AboutLabel = QtWidgets.QLabel(self.AboutPage)
        self.AboutLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.AboutLabel.setFont(font)
        self.AboutLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AboutLabel.setObjectName("AboutLabel")
        self.verticalLayout_5.addWidget(self.AboutLabel)
        self.AboutTxt = QtWidgets.QLabel(self.AboutPage)
        self.AboutTxt.setObjectName("AboutTxt")
        self.verticalLayout_5.addWidget(self.AboutTxt)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.AboutPage)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.AboutPage)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.AboutPage)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_14 = QtWidgets.QLabel(self.AboutPage)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.label_4 = QtWidgets.QLabel(self.AboutPage)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.AboutPage)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.WidgetPages.addWidget(self.AboutPage)
        self.horizontalLayout.addWidget(self.WidgetPages)
        self.gridLayout.addWidget(self.Widget_Contents, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        # Calling the retranslateUi-method to set the text of all labels
        self.retranslateUi(MainWindow)
        self.WidgetPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Creating lists containing the status of the robots in the different demos
        self.statusListRobo1Demo1 = ["Demo 1 is not running",
                                    "Starting demo 1",
                                    "Localizing first square",
                                    "Gripping first square",
                                    "Waiting for robot 2 to get ready",
                                    "Localizing landmark on square tray",
                                    "Placing first square in tray",
                                    "Localizing second square",
                                    "Gripping second square",
                                    "Placing second square in tray",
                                    "Grabbing the square tray",
                                    "Putting down the square tray"]

        self.statusListRobo2Demo1 = ["Demo 1 is not running",
                                    "Doing something else 2",
                                    "Messing around 3",
                                    "Making robot movements 4",
                                    "Hello world 5"]

        self.statusListRobo1Demo2 = ["Demo 2 is not running",
                                    "Doing something else 2",
                                    "Messing around 3",
                                    "Making robot movements 4",
                                    "Hello world 5"]

        self.statusListRobo2Demo2 = ["Demo 2 is not running",
                                    "Doing something else 2",
                                    "Messing around 3",
                                    "Making robot movements 4",
                                    "Hello world 5"]

        self.statusListRobo1Demo3 = ["Demo 3 is not running",
                                    "Starting demo 3",
                                    "Waiting for Robot 2 to scan \n landmark",
                                    "Waiting for mobile robot",
                                    "Scanning tray",
                                    "Picking up first planet gear",
                                    "Waiting for Robot 2 to reach \n collaborative area",
                                    "Placing first planet gear",
                                    "Picking up second planet gear",
                                    "Placing second planet gear",
                                    "Picking up third planet gear",
                                    "Placing third planet gear",
                                    "Picking up sun gear",
                                    "Inserting the sun gear",
                                    "Locking sun gear ring",
                                    "Picking up internal assembly",
                                    "Waiting for ring gear",
                                    "Aligning internal gear",
                                    "Inserting internal gear \n into ring gear",
                                    "Confirm correct placement \n of internal gear assembly",
                                    "Robot 1 finished task"]

        self.statusListRobo2Demo3 = ["Demo 3 is not running",
                                    "Starting demo 3",
                                    "Waiting for Robot 1 to be \n ready for landmark configuration",
                                    "Scanning landmark on Robot 1",
                                    "Waiting for mobile robot",
                                    "Scanning landmark on mobile robot",
                                    "Wrong tray scanned. \n Scanning other tray",
                                    "Correct tray confirmed",
                                    "Picking up planet gear holder",
                                    "Waiting for Robot 1 to \n finish task",
                                    "Moving to remove grippers",
                                    "Grippers removed.\n Scanning tray on mobile robot",
                                    "Picking up ring gear",
                                    "Moving to collaborative area",
                                    "Moving to mobile robot \n to place finished product",
                                    "Finished product placed",
                                    "Robot 2 finished task",
                                    "Moving to scan landmark \n on Robot 1"]

        self.statusListMobRob = ["Demo 3 is not running",
                                 "Going to pick up point",
                                 "Waiting for parts to be \n placed on robot. \n\n Press \n \"Confirm Parts Placed\" \n when parts are placed.",
                                 "Going to Robot 2",
                                 "Waiting for Robot 2 \n to pick up parts",
                                 "Going to Robot 1",
                                 "Waiting for Robot 1 \n to pick up parts",
                                 "Going to Robot 2",
                                 "Waiting for Robot 2 \n to place finished product",
                                 "Going to drop off point",
                                 "Arrived at drop off point",
                                 "Mission Accomplished",
                                 "Going to idle"]

        # Method for setting the text of labels and buttons in the GUI
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Collaborative Robots in Manulab"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LogoPrefix/Intro-Pic-Cobot-Page-1.png\"/></p></body></html>"))
        self.whichDemoIsRunLabel.setText(_translate("MainWindow", "No demo is currently running"))
        self.Demo1PageBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Modbus is not connected"))
        self.Demo1PageBtn.setText(_translate("MainWindow", "Demo 1: Easy Collaborative Task"))
        self.Demo2PageBtn.setText(_translate("MainWindow", "Demo 2: Simple Gear Assembly"))
        self.Demo3PageBtn.setText(_translate("MainWindow", "Demo 3: Advanced Gear Assembly"))
        self.AboutPageBtn.setText(_translate("MainWindow", "About this project"))
        self.modbusConnectBtn.setText(_translate("MainWindow", "Connect Modbus Server"))
        self.modbusDisconnectBtn.setText(_translate("MainWindow", "Disconnect Modbus Server"))
        self.Demo1Label.setText(_translate("MainWindow", "Demo 1: Easy Collaborative Task"))
        self.label_7.setText(_translate("MainWindow", "Current task of Robot 1"))
        self.label_8.setText(_translate("MainWindow", "Current task of Robot 2"))
        self.StartDemo1Btn.setText(_translate("MainWindow", "Start Demo 1"))
        self.StopDemo1Btn.setText(_translate("MainWindow", "Stop Demo 1"))
        self.Demo2Label.setText(_translate("MainWindow", "Demo 2: Simple Gear Assembly"))
        self.label_9.setText(_translate("MainWindow", "Current task of Robot 1"))
        self.label_11.setText(_translate("MainWindow", "Current task of Robot 2"))
        self.StartDemo2Btn.setText(_translate("MainWindow", "Start Demo 2"))
        self.StopDemo2Btn.setText(_translate("MainWindow", "Stop Demo 2"))
        self.Demo3Label.setText(_translate("MainWindow", "Demo 3: Advanced Gear Assembly"))
        self.label_10.setText(_translate("MainWindow", "Current task of Robot 1"))
        self.AssemblyConfirmBtn.setText(_translate("MainWindow", "Confirm Assembly"))
        self.label_13.setText(_translate("MainWindow", "Current task of Robot 2"))
        self.MobRobStatusLabel.setText(_translate("MainWindow", "Mobile Robot"))
        self.MobRobConfirmBtn.setText(_translate("MainWindow", "Confirm Parts Placed"))
        self.StartDemo3Btn.setText(_translate("MainWindow", "Start Demo 3"))
        self.StopDemo3Btn.setText(_translate("MainWindow", "Stop Demo 3"))
        self.AboutLabel.setText(_translate("MainWindow", "About this project"))
        self.AboutTxt.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">This system was created by a group of automation engineering students at NTNU in Aalesund.<br/>The system was created as part of a project in the Mechatronics subject.<br/>The purpose of the project was to make the robots collaborate on a complex task, using vision and a force sensor.</span></p><p><span style=\" font-size:18pt;\">The group consisted of the following students:<br/>Isak Gamnes Sneltvedt<br/>Erik Bjørnøy<br/>Erlend Holseker<br/>Arvin Khodabandeh</span></p><p><span style=\" font-size:18pt;\">The collaborative robots in the Manulab are delivered by Omron.</span></p></body></html>"))
        #self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LogoPrefix/robot_PNG79.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LogoPrefix/thinkingrobot.png\"/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LogoPrefix/standard_logo_ntnu_u-slagord.png\"/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LogoPrefix/OMRON_Logo.svg.png\"/></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LogoPrefix/amatec.png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LogoPrefix/Python_logo_and_wordmark.svg.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "This HMI is powered by Python."))
import Logo_rc

# Class used to connect the Page Selector buttons to the different pages
class ControlMainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(ControlMainWindow, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Set the Assembly Confirm Button invisible
        self.ui.AssemblyConfirmBtn.setVisible(False)

        # Starting a thread to listen for inputs from PLC
        self.listenThread = Thread(target=self.readModbusInputs, args=())
        self.listenThread.daemon = True
        self.startListenThread()

        # Starting a thread to use for monitoring server connection
        self.connectingThread = Thread(target=self.connectingServer, args=())
        self.connectingThread.daemon = True
        self.startConnectingThread()

        # Connecting the buttons
        self.ui.Demo1PageBtn.clicked.connect(lambda : self.ui.WidgetPages.setCurrentIndex(0))
        self.ui.Demo2PageBtn.clicked.connect(lambda : self.ui.WidgetPages.setCurrentIndex(1))
        self.ui.Demo3PageBtn.clicked.connect(lambda : self.ui.WidgetPages.setCurrentIndex(2))
        self.ui.AboutPageBtn.clicked.connect(lambda : self.ui.WidgetPages.setCurrentIndex(3))

        # Connecting GUI buttons to Modbus
        self.ui.StartDemo1Btn.pressed.connect(lambda : server.sendBool(9000, [bool(True)]))
        self.ui.StopDemo1Btn.pressed.connect(lambda : server.sendBool(9000, [bool(False)]))
        self.ui.StartDemo2Btn.pressed.connect(lambda : server.sendBool(9001, [bool(True)]))
        self.ui.StopDemo2Btn.pressed.connect(lambda : server.sendBool(9001, [bool(False)]))
        self.ui.StartDemo3Btn.pressed.connect(lambda : server.sendBool(9002, [bool(True)]))
        self.ui.StopDemo3Btn.pressed.connect(lambda : server.sendBool(9002, [bool(False)]))
        #self.ui.MobRobConfirmBtn.pressed.connect(lambda : server.sendBool(9003, [bool(True)]))

        #self.ui.MobRobConfirmBtn.setVisible(False)

    def startListenThread(self):
        self.listenThread.start()
        return self

    def readModbusInputs(self):
        while True:
            self.ui.ModbusInputDemo1Rob1.setText(self.ui.statusListRobo1Demo1[server.readInt(1000)[0]])
            self.ui.ModbusInputDemo1Rob2.setText(self.ui.statusListRobo2Demo1[server.readInt(1001)[0]])
            self.ui.ModbusInputDemo2Rob1.setText(self.ui.statusListRobo1Demo2[server.readInt(1002)[0]])
            self.ui.ModbusInputDemo2Rob2.setText(self.ui.statusListRobo2Demo2[server.readInt(1003)[0]])
            self.ui.ModbusInputDemo3Rob1.setText(self.ui.statusListRobo1Demo3[server.readInt(1004)[0]])
            self.ui.ModbusInputDemo3Rob2.setText(self.ui.statusListRobo2Demo3[server.readInt(1005)[0]])
            self.ui.ModbusInputMobRob.setText(self.ui.statusListMobRob[server.readInt(1006)[0]])

            self.ui.AssemblyConfirmBtn.setVisible(server.readBool(9008)[0])

            # Disabling buttons for starting other demos when one demo is running
            if server.readBool(9005)[0]:
                self.ui.StartDemo2Btn.setDisabled(True)
                self.ui.StartDemo3Btn.setDisabled(True)
                self.ui.whichDemoIsRunLabel.setText("Demo 1 is running")
            elif server.readBool(9006)[0]:
                self.ui.StartDemo1Btn.setDisabled(True)
                self.ui.StartDemo3Btn.setDisabled(True)
                self.ui.whichDemoIsRunLabel.setText("Demo 2 is running")
            elif server.readBool(9007)[0]:
                self.ui.StartDemo1Btn.setDisabled(True)
                self.ui.StartDemo2Btn.setDisabled(True)
                self.ui.whichDemoIsRunLabel.setText("Demo 3 is running")
            elif (server.readBool(9005)[0] is not True and server.readBool(9006)[0] is not True
                and server.readBool(9007)[0] is not True):
                self.ui.StartDemo1Btn.setDisabled(False)
                self.ui.StartDemo2Btn.setDisabled(False)
                self.ui.StartDemo3Btn.setDisabled(False)
                self.ui.whichDemoIsRunLabel.setText("No demo is currently running")

            # Parts placed confirm button
            if self.ui.MobRobConfirmBtn.isDown():
                server.sendBool(9003, [bool(True)])
            else:
                server.sendBool(9003, [bool(False)])

            # Assembly confirm button
            if self.ui.AssemblyConfirmBtn.isDown():
                server.sendBool(9004, [bool(True)])
            else:
                server.sendBool(9004, [bool(False)])

    def startConnectingThread(self):
        self.connectingThread.start()
        return self

    def connectingServer(self):
        serverHasBeenConnected = False
        while True:
            if self.ui.modbusConnectBtn.isDown():
                try:
                    server.connectServer()
                except Exception as e:
                    print(e)
                    self.ui.label_12.setText("Unable to connect. Check connection.")

            if self.ui.modbusDisconnectBtn.isDown():
                server.disconnect()
            if server.isConnected():
                self.ui.label_12.setText("Modbus is connected")
                serverHasBeenConnected = True

            if server.isConnected() is not True and serverHasBeenConnected:
                self.ui.label_12.setText("Modbus is not connected")

# Main function for running the GUI Application
if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mySW = ControlMainWindow()
    mySW.show()

    sys.exit(app.exec_())
    server.disconnect()
